package com.fleafinder.persistence.entity;

public enum RoleEnum {
    ADMIN,      // CREATE_FAIR, READ_FAIR, UPDATE_FAIR, DELETE_FAIR, VALIDATE_FAIR, MANAGE_REPORTS, MANAGE_USERS, SEND_ALERTS
    SELLER,     // CREATE_PRODUCT, READ_PRODUCT, UPDATE_PRODUCT, DELETE_PRODUCT, UPDATE_PROFILE, READ_PROFILE, REQUEST_FAIR
    BUYER,      // READ_PRODUCT, READ_FAIR, CREATE_REVIEW, UPDATE_REVIEW, DELETE_REVIEW, UPDATE_PROFILE, READ_PROFILE, REPORT_REVIEW, REQUEST_FAIR
    ORGANIZER   // CREATE_FAIR, READ_FAIR, UPDATE_FAIR, VALIDATE_FAIR
}